# Generated by Django 4.2.3 on 2023-11-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail_access_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
