# Generated by Django 4.2.3 on 2023-11-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gmail_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gmail_google_user_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_profile_image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
