# Generated by Django 4.2.3 on 2023-11-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gmail_email_user_gmail_google_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail_refresh_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
