# Generated by Django 4.2.3 on 2023-11-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gmail_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_drive_access_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_drive_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_drive_google_user_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_drive_refresh_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
