# Generated by Django 4.2.3 on 2023-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_google_calendar_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_access_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slack_user_email',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
