# Generated by Django 4.2.3 on 2023-10-18 19:10

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_remove_chathistory_source_links_chathistory_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='query',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='response',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='message_type',
            field=models.CharField(blank=True, choices=[('human', 'human'), ('ai', 'ai')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='original_document_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='ChatHistoryReference',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chatsession'),
        ),
    ]
