# Generated by Django 4.2.3 on 2023-10-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_notionpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionpage',
            name='url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
