# Generated by Django 4.2.3 on 2023-10-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_notionpage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notionpage',
            name='subpage_counts',
        ),
        migrations.AddField(
            model_name='notionpage',
            name='page_id',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
