# Generated by Django 4.2.3 on 2023-10-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_remove_datasyncstatus_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionpage',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notionpage',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
