# Generated by Django 4.2.3 on 2023-11-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_datasource_datasyncstatus_account_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasyncstatus',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RemoveConstraint(
            model_name='datasyncstatus',
            name='user source unique',
        ),
        migrations.RemoveField(
            model_name='datasyncstatus',
            name='source',
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source',
            field=models.CharField(blank=True, choices=[('notion', 'notion'), ('google_calendar', 'google_calendar'), ('gmail', 'gmail'), ('google_drive', 'google_drive'), ('slack', 'slack'), ('github', 'github')], null=True),
        ),
        migrations.AlterField(
            model_name='originaldocument',
            name='source',
            field=models.CharField(blank=True, choices=[('notion', 'notion'), ('google_calendar', 'google_calendar'), ('gmail', 'gmail'), ('google_drive', 'google_drive'), ('slack', 'slack'), ('github', 'github')], null=True),
        ),
    ]
