# Generated by Django 4.2.3 on 2023-11-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_alter_datasyncstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='sort_order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
